'use strict';

const WIT_TOKEN = 'VLWAM7XRBNNHIFWRBMHGQ3MNRA3XWSUG';
if (!WIT_TOKEN) {
  throw new Error('missing WIT_TOKEN');
}

const FB_PAGE_TOKEN = 'EAAChxwhHEXUBAAYRhVLaAGLfm8p0PQrV7965dvhqsAshZAEi0AjswhThN8dMskAM2FyDx9kZBf1AWThp3Ku66NBjAHklZC0wlk9bs2bhi1Enkcj4pSF0WilyYBcwWFXh0ZA3wSZCy91ZBf0YOGdipZC50q9bZCjL3DfSq1o74ZCg8bgeJEmK8vI05362wGO4yOK8ZD';

const GOOGLE_SHEET_ID = '1NvFE2p4k-RO4YciQ1wEvOUAvXdTqexIxpxK8PBX7JgQ';

module.exports = {
  WIT_TOKEN: WIT_TOKEN,
  FB_PAGE_TOKEN: FB_PAGE_TOKEN,
  GOOGLE_SHEET_ID: GOOGLE_SHEET_ID,
};